name: Delete All Releases and Tags

on:
  workflow_dispatch:  # 手动触发

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        uses: cli/cli-action@v1

      - name: Delete all GitHub releases
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Fetching releases..."
          gh release list --limit 1000 | awk '{print $1}' | while read tag; do
            echo "Deleting release: $tag"
            gh release delete "$tag" -y
          done

      - name: Delete all remote git tags
        run: |
          echo "Fetching tags..."
          git fetch --tags
          for tag in $(git tag); do
            echo "Deleting tag: $tag"
            git push origin :refs/tags/$tag
          done
