name: Delete All Releases and Tags

on:
  workflow_dispatch:  # 手动触发

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许删除 tags
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: gh auth setup-git

      - name: Delete all GitHub Releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Deleting all releases..."
          for release in $(gh release list --limit 1000 | awk '{print $1}'); do
            echo "Deleting release $release"
            gh release delete "$release" -y
          done

      - name: Delete all remote git tags
        run: |
          echo "Deleting all tags..."
          git fetch --tags
          for tag in $(git tag); do
            echo "Deleting tag $tag"
            git push origin :refs/tags/$tag
          done
